source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RFDuino_Example', :exclusive => true do
  pod 'RFDuino', :path => '../'
end

target 'RBLNano-Example', :exclusive => true do
    pod 'RFDuino', :path => '../'
end

target 'RFDuino_Tests', :exclusive => true do
  pod 'RFDuino', :path => '../'
  
end
