source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RFDuino_Example' do
  pod 'RFDuino', :path => '../'
end

target 'RBLNano-Example' do
    pod 'RFDuino', :path => '../'
end

target 'RFDuino_Tests' do
  pod 'RFDuino', :path => '../'

end
